# Generated by Django 2.2.9 on 2020-01-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentario',
            table='Comentario',
        ),
        migrations.AlterModelTable(
            name='mascota',
            table='Mascota',
        ),
        migrations.AlterModelTable(
            name='pretendiente',
            table='Pretendiente',
        ),
        migrations.AlterModelTable(
            name='publicacion',
            table='Publicacion',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
